module.exports = {
  theme: {
    width: {
      screen: '100vw',
      full: '100%',
      '1/2': '50%',
      '1/4': '25%'
    },
    screens: {},
    extend: {},
    colors: {
      transparent: 'transparent',
      black: {
        default: '#000',
        80: 'rgba(0, 0, 0, 0.87)',
        60: 'rgba(0, 0, 0, 0.68)',
        50: 'rgba(0, 0, 0, 0.56)',
        40: 'rgba(0, 0, 0, 0.38)'
      },
      grey: {
        default: '#a0a2ad',
        1: '#f8f9fc',
        2: '#eaecf1',
        3: '#dddde4',
        4: '#c9cad3',
        5: '#a0a2ad'
      },
      white: '#fff',
      primary: {
        default: '#2583e3',
        dark: '#1d68b5'
      },
      secondary: {
        grey: '#dddde4',
        blue: '#1d68b5'
      },
      toast: {
        default: '#ff4c00',
        1: '#ffe2d9',
        2: '#ffa98e',
        3: '#ff4c00',
        4: '#cc5935',
        5: '#994328',
        red: '#ff4c00',
        burnt: '#cf4000'
      }
    },
    borderRadius: {
      none: '0',
      default: '.25rem',
      full: '9999px'
    }
  },
  variants: {
    accessibility: [],
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: [],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: [],
    cursor: [],
    display: [],
    fill: [],
    flex: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: [],
    fontFamily: [],
    fontSize: [],
    fontSmoothing: [],
    fontStyle: [],
    fontWeight: [],
    height: [],
    inset: [],
    justifyContent: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: [],
    order: [],
    outline: [],
    overflow: [],
    padding: [],
    placeholderColor: [],
    pointerEvents: [],
    position: [],
    resize: [],
    stroke: [],
    tableLayout: [],
    textAlign: [],
    textColor: [],
    textDecoration: [],
    textTransform: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: [],
    wordBreak: [],
    zIndex: []
  },
  plugins: []
}
